### ISSUE TITLE
Some Metadata missing when creating ARC from OMERO

### ISSUE THREAD

**Issue by Nirkan** [cmohl2013/omero-arc#5]
I tried to create ARC from OMERO. I can see all the metadata there with namespaces.

However when I try to create an ARC in my local machine. I see that some metadata is missing.

For Example : 

In the ARC that I created in the local machine with omero-arc plugin I found in that in the isa.assay.xlsx the  Assay Performers metadata was missing. 

The issue was same in other ARCs created using omero-arc plugin.

**Comment by cmohl2013** [comment]
Which version of ARCCommander do you have installed?

**Comment by cmohl2013** [comment]
Which expected metadata is missing?
Do you see any related error messages? If yes, can you post them here?

**Comment by Nirkan** [comment]
Sorry for the delaied response : 

The version of ARCCommander was v0.5.0

**Comment by Nirkan** [comment]
The following expected metadata is usually missing : 

ASSAY PERFORMERS
--
Last Name
First Name
Mid Initials
Email
Phone
Fax
Address
Affiliation
Roles
Roles Term Accession Number
Roles Term Source REF
Comment[<Worksheet>]

**Comment by Nirkan** [comment]
I get the following errors. However it seems to be unrelated to the the missing Assay metadata.

```
Start Study Init 
ERROR: Study file already exists. 
Start Study Register 
ERROR: Study with the identifier ark1-cytoskeletal-localisation already exists in the investigation file. 
```

```
`ERROR: System.Exception: Metadata sheetname Investigation could not be found System.Exception: Metadata sheetname Investigation could not be found
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at ArcCommander.APIs.AssayAPI.Contacts.register(ArcConfiguration arcConfiguration, FSharpMap`2 personArgs)
   at ArcCommander.Program.handleAssayContactsSubCommands@128-2.Invoke(ArcConfiguration arcConfiguration, FSharpMap`2 personArgs)
   at ArcCommander.Program.processCommand[a,T](ArcConfiguration arcConfiguration, FSharpFunc`2 commandF, ParseResults`1 r)
   at ArcCommander.Program.handleAssayContactsSubCommands(ArcConfiguration arcConfiguration, AssayPersonCommand contactsVerb)
   at ArcCommander.Program.handleAssaySubCommands(ArcConfiguration arcConfiguration, AssayCommand assayVerb)
   at ArcCommander.Program.handleCommand(ArcConfiguration arcConfiguration, ArcCommand command)
   at ArcCommander.Program.main(String[] argv)
`
```

**Comment by cmohl2013** [comment]
@Nirkan can you install the newest version of ARCCommander and try again?

**Comment by Nirkan** [comment]
I tried with v1.0.0-preview.2 and I still do not get the right 'Assay performers' metadat

I only get my Last Name, First Name and Email. However Assay performer metadata is different as I used an ARC which belong to another person. The script seems to read Assay performer metadata directly from omero account and not from the metadata.

Note : If you have access, you can also see this metadata in the OMERO-ARC group with ProjectId: 1313 and DatasetID: 2367
